// FilterTabs
export const SET_FROM_FILTER_TAB = "SET_FROM_FILTER_TAB";
export const SET_TO_FILTER_TAB = "SET_TO_FILTER_TAB";
export const RESET_FILTER_TABS = "RESET_FILTER_TABS";

// CurrencySelect
export const SET_FROM_CURRENCY = "SET_FROM_CURRENCY";
export const SET_TO_CURRENCY = "SET_TO_CURRENCY";

// Filter
export const GET_FILTER_REQUEST = "GET_FILTER_REQUEST";
export const GET_FILTER_SUCCESS = "GET_FILTER_SUCCESS";
export const GET_FILTER_FAILED = "GET_FILTER_FAILED";

// Directions
export const GET_DIRECTIONS_REQUEST = "GET_DIRECTION_REQUEST";
export const GET_DIRECTIONS_SUCCESS = "GET_DIRECTIONS_SUCCESS";
export const GET_DIRECTIONS_FAILED = "GET_DIRECTIONS_FAILED";
